### ISSUE TITLE
Question about Football App

### ISSUE THREAD

**Issue by maywadee** [manijak/nativescript-photoviewer#1]
To whom it may concern @manijak , This is my Github account @liverbool
Regarding from this link https://www.nativescript.org/showcases , I’m interested in your Football App and would like to buy your app code (Only App code excluding API Backend). I would like to know whether you sell it or not.
Please accept my sincere apologies for writing to you in Github Issue, because I couldn’t find your email.

Sincerely,

**Comment by manijak** [comment]
Hi there @maywadee, sorry for the late reply. 
Currently the code is not for sale, it's owned by the club. And until that changes, we will not be selling it,  sorry. :)
