### ISSUE TITLE
Xcode build fail

### ISSUE THREAD

**Issue by sydeEvans** [manijak/nativescript-photoviewer#10]
package.json

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.baisiApp",
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "nativescript-angular": "1.5.1",
    "nativescript-photoviewer": "^1.0.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "2.5.2",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "typescript": "~2.1.0"
  }
}
```

- tns run ios
- open platforms/ios  in xcode 
- build fail
<img width="1391" alt="dingtalk20170405191016" src="https://cloud.githubusercontent.com/assets/15522856/24704708/5f966796-1a3b-11e7-8e03-f92596322fe5.png">

**Comment by manijak** [comment]
Sorry, but I'm unable to reproduce your error. I've tried both on NativeScript Core and Angular with the latest version, using Xcode 8.3.1, and the app runs fine. Your problem must lie elsewhere. 

Try cleaning your platforms and re-adding them. Or if you could provide a demo app with the issue I'll be glad to take a look at it.

**Comment by karlatt** [comment]
This is a XCode cocoapod problem , it happens with lots of plugins in Ios...
Shoiuld define your podRoot directory in the 2 [cp] scripts which are ran pre and post build..Can find those in the Build Phases tab when you have selected youir target in XCode...
Hope it helps
