### ISSUE TITLE
Skip gallery view in android?

### ISSUE THREAD

**Issue by davecoffin** [manijak/nativescript-photoviewer#11]
Hi there, I have a custom gallery view, and I want to skip the gallery view in this implementation. Is that possible? When I call showViewer, the array has a single url in it, so theres no need to display the thumbnail gallery.

**Comment by manijak** [comment]
Hi. This nativescript plugin is just a wrapper around a gradle plugin, so I just expose the functionality that is already present there. I remember someone else asked the original author about the same thing, and he said that is not possible right now. https://github.com/lawloretienne/ImageGallery/

I should perhaps find another gradle plugin that does exactly that and use that instead.

**Comment by davecoffin** [comment]
Gotcha. That would be awesome.

**Comment by manijak** [comment]
Fullscreen gallery now added to version 1.4.0, use it by setting `showAlbum=false` on the photoViewer instance.

**Comment by davecoffin** [comment]
Amazing! Thanks so much, it works great.
