### ISSUE TITLE
Feature request: Please add option to set the title of the gallery and set the background color

### ISSUE THREAD

**Issue by shiv19** [manijak/nativescript-photoviewer#15]
Since the underlying plugin supports these feature, can you please add it to the wrapper?

something like
photoViewer.showViewer(imageList, "Title", "VIBRANT");

background types to be one among
VIBRANT
LIGHT_VIBRANT
DARK_VIBRANT
MUTED
LIGHT_MUTED
DARK_MUTED

**Comment by manijak** [comment]
The title key was not available, background color palettes added in version 1.4.0
