### ISSUE TITLE
How can I load photos from local files in Android?

### ISSUE THREAD

**Issue by mutazmq** [manijak/nativescript-photoviewer#17]
Hi

The plugin doesn't render photos when I pass the URL as a local file path. I'm developing an Android app, how can I pass local files to the photo viewer?

Thanks

**Comment by DivyeshSharma** [comment]
Hello mutazmq
You can pass the URL as a local file path by adding "file://" in local file path. Local file path : storage/emulated/0/SheyeApp/Images/Sent/350ec9b2-f776-a669-30ab-348ed890825f.jpg add "file://"
so it look like file://storage/emulated/0/SheyeApp/Images/Sent/350ec9b2-f776-a669-30ab-348ed890825f.jpg. Its Working fine for me.
