### ISSUE TITLE
Error: TypeError: Cannot read property 'ImageGalleryActivity' of undefined

### ISSUE THREAD

**Issue by LorenDorez** [manijak/nativescript-photoviewer#18]
I get an error 'TypeError: Cannot read property 'ImageGalleryActivity' of undefined' when i try to call showViewer with an imageUrl

```
photoViewer.showViewer(["http://192.168.1.12:52482/test.png"]);
```

**Comment by Mataninja** [comment]
+

**Comment by manijak** [comment]
Sorry but I just tested this today on both iOS and the latest SDK for Android, and it works fine.

**Comment by jolee11** [comment]
I have the same problem!

TypeError: Cannot read property 'ImageGalleryActivity' of undefined

**Comment by jolee11** [comment]
After "tns update" , problem solved!
