### ISSUE TITLE
Any way to open iOS gallery at a specific image?

### ISSUE THREAD

**Issue by FranciZ** [manijak/nativescript-photoviewer#19]
Would like to open the gallery at a specific index. Also, the close and share buttons are under the notification bar on the iPhone and hard to hit, is there a way around that?

Thanks!

**Comment by sushant-j** [comment]
Facing the second issue as well. Any workaround or solution will be much appreciated :)

**Comment by manijak** [comment]
Both will be taken care of in the next version.

**Comment by manijak** [comment]
Just released v1.3.0 to npm.
