### ISSUE TITLE
NYT Photo Issue

### ISSUE THREAD

**Issue by vchittar** [manijak/nativescript-photoviewer#2]
Hey, I came across this module while trying to implement a sort of a photo slider concept. Essentially what I have to do is to make a carousel like function which will enable me to cycle through certain pictures. 

But I have been running into this error recently:

file:///app/tns_modules/nativescript-photoviewer/index.js:91:25: JS ERROR ReferenceError: Can't find variable: NYTPhoto

And I cannot seem to figure out whats the problem. Could you please help regarding this issue, thanks!

**Comment by manijak** [comment]
Please post the code where you are using the plugin. The plugin works fine in the apps I use.

**Comment by vchittar** [comment]
var observable = require("data/observable");
var frameModule = require("ui/frame");


	//navigation via "+" button to the page with the notes
	//dont forget to change the values in app.js main page in order to establish contact
	exports.tapAction = function() 
{
    frameModule.topmost().navigate("notes");
}


exports.pageLoaded = function(args)
{
    var page = args.object;
    var viewModel = new observable.Observable();

// photo slider goes here




    

if(page.ios)

{
	 //we make a variable to control the iOS UI Bar 
	 var controller = frameModule.topmost().ios.controller;
	 
	 //now we are going to add the "+" button to this page so we can navigate properly 




};




}

**Comment by manijak** [comment]
I don't see the plugin used anywhere in the example you just added.

**Comment by vchittar** [comment]
I deleted it because it kept giving me the error, let me write the code for it and post it sorry!

**Comment by vchittar** [comment]
var observable = require("data/observable");
var frameModule = require("ui/frame");
var PhotoViewer = require("nativescript-photoviewer");



	//navigation via "+" button to the page with the notes
	//dont forget to change the values in app.js main page in order to establish contact
	exports.tapAction = function() 
{
    frameModule.topmost().navigate("notes");
}


exports.pageLoaded = function(args)
{
    var page = args.object;
    var viewModel = new observable.Observable();

// photo slider goes here


photoViewer = new PhotoViewer();

var imageFromURL1 = "https://www.google.com/images/errors/logo_sm_2.png";
var imageFromURL2 = "https://www.google.com/images/errors/logo_sm_2.png";

var myImages = [imageFromURL1, imageFromURL2];
photoViewer.showViewer(myImages);



    

if(page.ios)

{
	 //we make a variable to control the iOS UI Bar 
	 var controller = frameModule.topmost().ios.controller;
	 
	 //now we are going to add the "+" button to this page so we can navigate properly 




};




}

**Comment by manijak** [comment]
I just used the exact same code you posted here in a new app (copied your code), and it works without issues. 

You have installed the plugin correctly? 
`tns plugin add nativescript-photoviewer` 
Then do a `tns prepare ios` and `tns build ios`

The error you are getting is telling you that the CocoaPod, that the plugins is based on, is missing.

**Comment by vchittar** [comment]
But when I do have pod installed and when I do pod --version it gives me: 
Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:140: warning: Insecure world writable dir /Users/student/Desktop/Native_Script in PATH, mode 040777
1.0.1

**Comment by manijak** [comment]
Looks like a faulty cocapods configuration on your Mac. Think it's telling you that there are permissions issues with the following path: /Users/student/Desktop/Native_Script

**Comment by vchittar** [comment]
After tinkering with it a bit more I get this error: 

[WARNING]: [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Library` to `Pods/Target Support Files/Pods-Library/Pods-Library.debug.xcconfig` or include the `Pods/Target Support Files/Pods-Library/Pods-Library.debug.xcconfig` in your build configuration (`Library/build-debug.xcconfig`).

**Comment by manijak** [comment]
Yeah I get the same Warning, but it still works as it should

**Comment by vchittar** [comment]
Ok I think I fixed it, I updated the pod and it seemed to start working. Weird error. Another question: Is there a way for me to directly put the pictures on XML page rather than the photos being viewed in an another window?

**Comment by manijak** [comment]
Great! :)
No sorry, for this plugin, this is the only way to use it. 

If you would like a "carousel-effect" on a view, I could recommend the `nativescript-slides` plugin. 
https://www.npmjs.com/package/nativescript-slides

**Comment by vchittar** [comment]
I had used that before but I needed a "sliding" motion. Do you know if there is any way to create a slider so a user can use the slider to go to any picture rather than following the pictures in a sequential order?

**Comment by vchittar** [comment]
Hey, quick question. I noticed that when I add a title or summary for a picture, the picture either takes a very very long time to load or doesnt load at all? Is there any reason for that? 

Thanks!
