### ISSUE TITLE
iOS Photoviewer not showing

### ISSUE THREAD

**Issue by tuckerjt07** [manijak/nativescript-photoviewer#20]
When attempting to combine this plugin with the nativescript-imagepicker plugin I select an image from the picker and it appears photoviewer is failing with this error ```unrecognized selector sent to instance 0x7f9ccf9b4da0```.

The code is as follows
```
private _iOsViewPhoto(imageAsset: any) {
    const photoViewer = new PhotoViewer();
    const imageObj = {
      image: imageAsset.ios
    };
    
    photoViewer.showViewer([imageObj]);
    
  }
```

I am using the Angular Typescript flavor of NativeScript.

**Comment by Eonfuzz** [comment]
I've run into a similar thing myself (Except not getting any error logs).

Were you by any chance trying to run this inside a modal?
