### ISSUE TITLE
ERROR TypeError: Cannot read property 'FullScreenImageGalleryActivity' of undefined

### ISSUE THREAD

**Issue by RadouaneRoufid** [manijak/nativescript-photoviewer#21]
I installed the version `1.4.0` of `nativescript-photoviewer` in my `NativeScript-Angular` App. 

I got the following error when trying to display the gallery in an android emulator :

`ERROR TypeError: Cannot read property 'FullScreenImageGalleryActivity' of undefined`.

tns --version => 3.4.0
tns-android => 3.4.1
typescript => 2.4.0

**Comment by jolee11** [comment]
After "tns update", no such problem anymore!

**Comment by slasho** [comment]
did tns update and my project die... it breaked tns core =( so... update is not an option...

**Comment by slasho** [comment]
@manijak any ideas?

**Comment by pauly815** [comment]
I just ran into this problem on TNS 3.4.2 using 1.4.0.  I removed my platforms/android folder and re-ran tns run android and the error went away.
