### ISSUE TITLE
Gallery intermittently breaks in iOS

### ISSUE THREAD

**Issue by RichardM99** [manijak/nativescript-photoviewer#26]
Can replicate using the demo app provided in this repo.

Two issues seems to occur intermittently;

1. When you open the gallery with more than one photo, you are unable to swipe to the next or previous photo.

2. When swiping, the gallery seems to sometimes lose track of it's current index position. This results in the header text being incorrect (for example if it was "1 of 4" it will now read "1") and also results in missing photos i.e. where once before you could swipe between three photos you can now only swipe between two. For example, the image below has the wrong header as it's the second image 

<img width="369" alt="screen shot 2018-08-24 at 09 40 24" src="https://user-images.githubusercontent.com/8677446/44571878-6eb8ec00-a782-11e8-8253-0e155ae62196.png">

To replicate open any of the three galleries in the demo in this repo and start swiping. As mentioned, only happens intermittently so you need to just close and reopen the gallery if the issue does not occur and eventually you will come across the issues mentioned. Android everything seems to be working fine!

Could possibly be related to these issues ?

https://github.com/NYTimes/NYTPhotoViewer/issues/260

https://github.com/NYTimes/NYTPhotoViewer/issues/259

Let me know what you think!

Cheers

**Comment by manijak** [comment]
Thanks for the detailed feedback, will look into into as soon as I can :)

**Comment by RichardM99** [comment]
Thanks for the quick response 👍

**Comment by Sbpace** [comment]
Hi Manijak,
Do you know when this issue will be fixed? It is causing us some problems.

**Comment by manijak** [comment]
No ETA. Feel free to fork the repo and see if you could fix the issue yourself. PRs are welcome.

**Comment by Sbpace** [comment]
Thanks for the quick reply. We will take a look at the issue 👍

**Comment by RichardM99** [comment]
I have tested this using npm version 1.5.0 and still experiencing the same issue.

@miex0r  @manijak 

Could it be an issue with the version published on npm maybe ?

**Comment by RichardM99** [comment]
@manijak Hey thanks for taking another look. Are the latest changes published to npm ?

**Comment by manijak** [comment]
No not yet, need to make sure Android part still works, pluss update demos and readme. There will be a few breaking changes with the new version, but it will work better.

**Comment by RichardM99** [comment]
Thanks for the reply 👍
