### ISSUE TITLE
Photo Loading Issue

### ISSUE THREAD

**Issue by vchittar** [manijak/nativescript-photoviewer#3]
Hey, quick question. I noticed that when I add a title or summary for a picture, the picture either takes a very very long time to load or doesnt load at all? Is there any reason for that?

Thanks!

**Comment by manijak** [comment]
Hmm, have not noticed. Is this on iOS or Android? I've only created the nativescript wrapper around the functions that the pod and gradle expose :) You would have to report any performance issues to the original authors since I am not able to modify the pods.

**Comment by vchittar** [comment]
Sorry I solved this issue it was because the links were in http instead of https and NativeScript wasnt letting me use http.
