### ISSUE TITLE
Can't load photoviewer in my android project

### ISSUE THREAD

**Issue by progressify** [manijak/nativescript-photoviewer#37]
Hi
In my angular project, I want to use photo-viewer.
But when I try to call the `showViewer` method I receive this error:

`JS: ERROR TypeError: Cannot read property 'imagegallery' of undefined`

I use a Google Pixel 2 XL for testing with Android Pie.

**Comment by manijak** [comment]
Working on a new version, hopefully it will work better on angular as well.

**Comment by manijak** [comment]
Version 2.0.2 published to npm

**Comment by manijak** [comment]
New version published 2.1.0 added Angular demo app as well
