### ISSUE TITLE
PhotoViewer not opening after update

### ISSUE THREAD

**Issue by VeeK727** [manijak/nativescript-photoviewer#40]
I'm having some problem with PhotoViewer. I think I'm not running it correctly in JS. An example in JS would be great.

The problem is I'm not getting the gallery to show up on both Android and iOS. There are no errors in the console or on screen. Nothing happens. Its not the case of trying twice to show the gallery or zooming/panning to make it appear. I'm also not using a modal.

**Versions:**
NS CLI: 5.3.0
PhotoViewer: 2.0.2
Android: Pie (9)
iOS: 12.2

**Code:**
```
exports.toImageGallery = function(){
	var images = [];
	if(page.ios){
		loader.show(config.loadingOptions);
	}
	http.request({
		url: config.apiUrl+"/product-images.php",
		method: "POST",
		headers: { "Content-Type": "application/json" },
		content: JSON.stringify({
			auth: config.apiAuth,
			id: productVM.get("id")
		})
	}).then(function(request){
		var response = JSON.parse(request.content);
		images = response.data;
		console.log(images); //works as expected

		var photoViewer = new PhotoViewer();
		var photoviewerOptions = {
			startIndex: 0,
			ios: {
				completionCallback: galleryLoaded
			},
			android: {
				paletteType: PaletteType.DarkVibrant,
				showAlbum: false
			}
		};
		photoViewer.showGallery(images, photoviewerOptions);
		if(page.ios){
			loader.hide();
		}
	}, function(error){
		console.log(JSON.stringify(error));
	});
}

function galleryLoaded(){
	loader.hide();
}
```

**Comment by manijak** [comment]
I would recommend that you follow the guidelines from the demo app and readme. Start by initializing the PhotoViewer in the `onloaded` event.

**Comment by VeeK727** [comment]
With that I get an error "PhotoViewer is not a constructor". I did look at the demo but I need a JS example. What would be the JS equivalent of

```
import { PhotoViewer, PhotoViewerOptions, PaletteType, NYTPhotoItem } from "nativescript-photoviewer";
var photoViewer: PhotoViewer;
```
Currently I'm using this from the old version
```
const PhotoViewer = require("nativescript-photoviewer");
```

**Comment by manijak** [comment]
Just published version 2.1.1 and added a vanilla js demo app to git. Follow the guidelines there and it should work.

**Comment by VeeK727** [comment]
Thanks for the JS example. I've implemented it and the page is loading fine now. But when I click on the element to open the gallery it still giving me the old error: https://github.com/manijak/nativescript-photoviewer/issues/32

**Comment by VeeK727** [comment]
Hi @manijak Can you please release a fix?

**Comment by manijak** [comment]
Fix what? Everything runs fine here both iOS & Android. My config: 
```
tns-cli: 5.3.1
tns-ios: 5.3.1
tns-android: 5.3.1
core-modules: 5.3.1
photo-viewer: 2.1.1

iOS: 12.2
Android: SDK updated to lates, tested emulator api 27 & 28
```

Only suggestion I have is to clean your workspace by removing all platforms, node_modules and hooks folders. Rebuild and run.

**Comment by VeeK727** [comment]
I've updated everything and rebuilt the project twice. I'm still getting the error. Could you share your email/slack so I could share my project with you privately so you can have a look at it?

**Comment by VeeK727** [comment]
The problem is coming from Fresco plugin not Photoviewer. Thanks for your time.
