### ISSUE TITLE
Android Angular

### ISSUE THREAD

**Issue by microsoftlibrary** [manijak/nativescript-photoviewer#44]
ERROR in node_modules/nativescript-photoviewer/photoviewer.d.ts(47,22): error TS2304: Cannot find name 'UIColor'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(53,24): error TS2304: Cannot find name 'UIColor'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(59,23): error TS2304: Cannot find name 'UIColor'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(88,13): error TS2304: Cannot find name 'UIImage'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(93,24): error TS2304: Cannot find name 'UIImage'.

**Comment by manijak** [comment]
Would greatly appreciate if you could provide more information about the issue, not just the console output.

**Comment by manijak** [comment]
Btw: Published version 2.1.1 with photoviewer.d.ts included in case the error above had anything to do with missing typings.

**Comment by microsoftlibrary** [comment]
thanks,when i go back home,i will report you again.

**Comment by frozenmaiden** [comment]
Hi,

I got same issue

ERROR in node_modules/nativescript-photoviewer/photoviewer.d.ts(48,22): error TS2304: Cannot find name 'UIColor'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(54,24): error TS2304: Cannot find name 'UIColor'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(60,23): error TS2304: Cannot find name 'UIColor'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(89,13): error TS2304: Cannot find name 'UIImage'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(94,24): error TS2304: Cannot find name 'UIImage'.

Can advice how to resolve?

**Comment by microsoftlibrary** [comment]
@frozenmaiden no

**Comment by frozenmaiden** [comment]
I already found the issue, i need to put

/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />

under references.d.ts

**Comment by hermandinho** [comment]
Adding `"skipLibCheck": true,` in *tsconfig* solved it for me
