### ISSUE TITLE
Getting warnings during build in cli

### ISSUE THREAD

**Issue by OPADA-Eng** [manijak/nativescript-photoviewer#45]
Hi there,
I'm getting those warnings in the cli when I try to build the app

> node_modules/nativescript-photoviewer/photoviewer.d.ts(48,22): error TS2304: Cannot find name 'UIColor'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(54,24): error TS2304: Cannot find name 'UIColor'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(60,23): error TS2304: Cannot find name 'UIColor'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(89,13): error TS2304: Cannot find name 'UIImage'.
node_modules/nativescript-photoviewer/photoviewer.d.ts(94,24): error TS2304: Cannot find name 'UIImage'.

any way to remove them?

**Comment by tsonevn** [comment]
Hi @OPADA-Eng,
As a temporary solution, you can add [tns-platform-declarations](https://www.npmjs.com/package/tns-platform-declarations) as a dev dependency.

**Comment by OPADA-Eng** [comment]
@tsonevn  Thanks for response, but where should I put this dev dependency?

**Comment by manijak** [comment]
@OPADA-Eng You install it as a package. `npm i tns-platform-declarations`

**Comment by OPADA-Eng** [comment]
@manijak Actually I tried that but it didn't work, this errors affect building the app for release when I use webpack.
I have to remove this errors manually when I want to build the app for release each time.

**Comment by manijak** [comment]
Strange that the project is scanning the node_modules folder. Do you have `skipLibCheck: true` set in the `tsconfig.json`?

**Comment by OPADA-Eng** [comment]
@manijak this fixed the problem thanks!
