### ISSUE TITLE
Loading of local images

### ISSUE THREAD

**Issue by kwong93** [manijak/nativescript-photoviewer#5]
I could not load a local image in Android. I'm passing in `filePath`, which looks like this:

`/data/data/com.company.company/files/app/images/abc 123.png
`

This is how I get `filePath`:

```
            var documents = fsModule.knownFolders.documents();
            var imagesFolder = documents.getFolder('app').getFolder('images');

            var savePath = imagesFolder.path;
            var filePath = fsModule.path.join(savePath, fileName);
```

**Comment by manijak** [comment]
Yeah the plugin supports only remote images, not local.

**Comment by kwong93** [comment]
Actually I found a way to load images locally. I had to stick the string `file://` in front, so the final string you would pass in would look like this:

`file:///data/data/com.company.company/files/app/images/abc 123.png`
