### ISSUE TITLE
Expose the FullScreenImageGalleryActivity

### ISSUE THREAD

**Issue by kwong93** [manijak/nativescript-photoviewer#6]
For Android, could we have a way to use `FullScreenImageGalleryActivity`?

For example, option to open an image directly to full screen instead of going through the first screen where it displays the images in a grid.

**Comment by manijak** [comment]
@kwong93 Could you explain more on what you need here? I'm just exposing what the original android-plugin is offering.

**Comment by kwong93** [comment]
@manijak I've updated my initial comment.

**Comment by manijak** [comment]
Well that's the thing, since this plugin is just a js-wrapper for a android-library there is no way I can just expose it. 

Here is a comment from the author of the android-lib: https://github.com/lawloretienne/ImageGallery/issues/18

**Comment by manijak** [comment]
Fullscreen Image gallery added to 1.4.0
