### ISSUE TITLE
Does not build with Nativescript Angular

### ISSUE THREAD

**Issue by leocrawf** [manijak/nativescript-photoviewer#8]
This plugin needs to be updated to run with {n} 2.4.

**Comment by manijak** [comment]
Works fine here with 2.4. 
Can you provide more info as to what is not working? Platform, Exceptions, code samples? 
Thanks

**Comment by leocrawf** [comment]
My App could build until I added the plugin and modified the androidManifest.xml . This is the androidManifest.xml: 

        <?xml version="1.0" encoding="utf-8"?>
		<manifest xmlns:android="http://schemas.android.com/apk/res/android"
			package="__PACKAGE__"
			android:versionCode="1"
			android:versionName="1.0">

			<supports-screens
				android:smallScreens="true"
				android:normalScreens="true"
				android:largeScreens="true"
				android:xlargeScreens="true"/>

			<uses-sdk
				android:minSdkVersion="17"
				android:targetSdkVersion="__APILEVEL__"/>

			<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
			<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
			<uses-permission android:name="android.permission.INTERNET"/>

			<application
				android:name="com.tns.NativeScriptApplication"
				android:allowBackup="true"
				android:icon="@drawable/icon"
				android:label="@string/app_name"
				android:theme="@style/AppTheme">

				<activity
					android:name="com.tns.NativeScriptActivity"
					android:label="@string/title_activity_kimera"
					android:configChanges="keyboardHidden|orientation|screenSize"
					android:theme="@style/LaunchScreenTheme">

					<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

					<intent-filter>
						<action android:name="android.intent.action.MAIN" />
						<category android:name="android.intent.category.LAUNCHER" />
					</intent-filter>
				</activity>
				<activity
                              android:name="com.etiennelawlor.imagegallery.library.activities.ImageGalleryActivity"
					android:configChanges="orientation|keyboardHidden|screenSize"
					android:label=""
					android:theme="@style/ImageGalleryTheme" />
						
				<activity android:name="com.tns.ErrorReportActivity"/>

				<service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService" />
			</application>
		</manifest>

This is the error:
   C:\development\nativescript\StFrancis\platforms\android\build\intermediates\manifests\full\F0F1F2F3\debug\AndroidManifest.xm
        l:69:28-52: AAPT: No resource found that matches the given name (at 'theme' with value '@style/ImageGalleryTheme').

        :processF0F1F2F3DebugResources FAILED

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':processF0F1F2F3DebugResources'.
        > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Ten
        nesha\AppData\Local\Android\android-sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

        BUILD FAILED

        Total time: 57.961 secs
        Command C:\development\nativescript\StFrancis\platforms\android\gradlew.bat failed with exit code 1

**Comment by manijak** [comment]
Why did you modify the manifest file? I don't mention anything regarding that in the usage tutorial. 
Please try without modifying the file.

**Comment by leocrawf** [comment]
I am getting this error now after I have removed the entry from the androidManifest.xml: 
Error: com.tns.NativeScriptException: Failed to find module: "nativescript-photoviewer", relative to: app/tns_modules/

I checked the package.json:
{
  "nativescript": {
    "tns-android": {
      "version": "2.4.1"
    }
  },
  "dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.1.2",
    "nativescript-angular": "1.1.2",
    "nativescript-couchbase": "^1.0.13",
    "nativescript-mapbox": "^2.3.0",
    "nativescript-telerik-ui": "^1.4.1",
    "nativescript-theme-core": "^0.1.5",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.4.0"
  },
  "devDependencies": {
    "babel-traverse": "6.18.0",
    "babel-types": "6.18.0",
    "babylon": "6.13.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.8",
    "zone.js": "~0.6.21"
  }
}

After checking the tns_modules I noticed there is a nativescript-photoviewer folde. Maybe the verbose error message will help so I will post it here:

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:

Error calling module function

Error calling module function

Error calling module function

Error calling module function

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-photoviewer", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5339)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    dalvik.system.NativeStart.main(Native Method)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/clubs/clubs.component.js', line: 3, column: 19
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app-routing.module.js', line: 8, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app.module.js', line: 5, column: 28
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/main.js', line: 4, column: 20
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-photoviewer", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5339)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    dalvik.system.NativeStart.main(Native Method)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/clubs/clubs.component.js', line: 3, column: 19
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app-routing.module.js', line: 8, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app.module.js', line: 5, column: 28
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/main.js', line: 4, column: 20
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-photoviewer", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5339)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    dalvik.system.NativeStart.main(Native Method)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/clubs/clubs.component.js', line: 3, column: 19
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app-routing.module.js', line: 8, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app.module.js', line: 5, column: 28
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/main.js', line: 4, column: 20
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-photoviewer", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5339)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    dalvik.system.NativeStart.main(Native Method)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/clubs/clubs.component.js', line: 3, column: 19
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app-routing.module.js', line: 8, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app.module.js', line: 5, column: 28
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/main.js', line: 4, column: 20
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-photoviewer", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5339)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    dalvik.system.NativeStart.main(Native Method)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/clubs/clubs.component.js', line: 3, column: 19
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app-routing.module.js', line: 8, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app.module.js', line: 5, column: 28
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/main.js', line: 4, column: 20
Frame: function:'require', file:'', line: 1, column: 266

at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4591)
at android.app.ActivityThread.access$1500(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5339)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
at dalvik.system.NativeStart.main(Native Method)
Caused by: com.tns.NativeScriptException:

Error calling module function

Error calling module function

Error calling module function

Error calling module function

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-photoviewer", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5339)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    dalvik.system.NativeStart.main(Native Method)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/clubs/clubs.component.js', line: 3, column: 19
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app-routing.module.js', line: 8, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app.module.js', line: 5, column: 28
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/main.js', line: 4, column: 20
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-photoviewer", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5339)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    dalvik.system.NativeStart.main(Native Method)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/clubs/clubs.component.js', line: 3, column: 19
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app-routing.module.js', line: 8, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app.module.js', line: 5, column: 28
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/main.js', line: 4, column: 20
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-photoviewer", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5339)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    dalvik.system.NativeStart.main(Native Method)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/clubs/clubs.component.js', line: 3, column: 19
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app-routing.module.js', line: 8, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app.module.js', line: 5, column: 28
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/main.js', line: 4, column: 20
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-photoviewer", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5339)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    dalvik.system.NativeStart.main(Native Method)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/clubs/clubs.component.js', line: 3, column: 19
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app-routing.module.js', line: 8, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app.module.js', line: 5, column: 28
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/main.js', line: 4, column: 20
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-photoviewer", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5339)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    dalvik.system.NativeStart.main(Native Method)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/clubs/clubs.component.js', line: 3, column: 19
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app-routing.module.js', line: 8, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/modules/app.module.js', line: 5, column: 28
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.StFrancis/files/app/main.js', line: 4, column: 20
Frame: function:'require', file:'', line: 1, column: 266

at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:514)
at com.tns.Runtime.run(Runtime.java:509)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
... 10 more

**Comment by manijak** [comment]
Yeah, you are using angular version of NativeScript, that is why. 
Sorry, but for now, NG2 is not supported. The plugin was made way before NG2 was available.  Never tested it there...

**Comment by leocrawf** [comment]
Noted! Any plans on making it ng ready?

**Comment by manijak** [comment]
For sure, but no ETA. Especially since I haven't touched ng2 yet :)

**Comment by manijak** [comment]
I did a quick test now on the ng2 sample app (groceries). Installed the plugin and ran it both on iOS and Android without any issues. 

I see that you are missing the plugin in the package.json file under dependencies. That is why you are getting that error. 

Add this to dependencies. 
`"nativescript-photoviewer": "1.0.0"`

**Comment by leocrawf** [comment]
Thank you. I will certainly give this a try again.

**Comment by Leo-lay** [comment]
@manijak i have the same issue,i use ng to implement this plugin,when i use follow code

`var PhotoViewer = require("nativescript-photoviewer");`

 it's appear 

 `Could not find module 'nativescript-photoviewer'.`

but in my node_module had installed plugin.

any help ?

**Comment by leocrawf** [comment]
Make sure you have "nativescript-photoviewer": "1.0.0" or some other version, in package.json file.

**Comment by leocrawf** [comment]
Yes it now works.
